allocation/urls.py
from django.urls import path
from allocation import views

app_name = 'allocation'
urlpatterns = [
    path("", views.index.as_view(), name="index"),
    path("signup", views.signup.as_view(user_type="student"), name="student_signup"),
    path("login", views.login.as_view(user_type="student"), name="student_login"),
    path("allocate/<int:user_id>/<slug:room_number>", views.roomAllocate.as_view(), name="room_allocate"),
    path("logout", views.user_logout.as_view(), name="logout"),
]

room_allocation/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('allocation.urls', namespace='allocation')),
]

allocation/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

# Create your models here.
class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email), **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password, **extra_fields):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email=email,
            password=password, **extra_fields
        )
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email=email,
            password=password, **extra_fields
        )
        user.is_staff = True
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class User(AbstractUser):
    username = None     # https://docs.djangoproject.com/en/3.2/topics/db/models/#field-name-hiding-is-not-permitted
    user_id = models.AutoField(primary_key=True, editable=False)
    email = models.EmailField(max_length=100, unique=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    password = models.CharField(max_length=255)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'password']

    def get_full_name(self):
        return self.first_name + " " + self.last_name
    
    def get_short_name(self):
        return self.first_name
    
    def __str__(self):
        return self.email

class Student(models.Model):
    user = models.OneToOneField(User, related_name='student', on_delete=models.CASCADE)
    roll_number = models.CharField(max_length=20, unique=True)
    is_allotted = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=20)

    def get_full_name(self):
        return self.user.first_name + " " + self.user.last_name

    def __str__(self):
        return self.user.email

class Room(models.Model):
    room_number = models.CharField(max_length=20, unique=True)
    roll_number = models.CharField(max_length=20, default="0")

    def __str__(self):
        return self.room_number

allocation/views.py
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib.auth import authenticate
from rest_framework import status
from django.contrib.auth.hashers import make_password
from rest_framework.renderers import TemplateHTMLRenderer
from django.http import JsonResponse
from django.contrib.auth import logout
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import render, redirect

from .models import User, Student, Room
from .serializers import UserSerializer, StudentSerializer, RoomSerializer

class index(APIView):
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):
        return Response(template_name="index.html", status=status.HTTP_200_OK)
        
class signup(APIView):
    user_type = "student"
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):
        if(self.user_type=="student"):
            return Response(template_name="student_signup.html", status=status.HTTP_200_OK)

    def post(self, request):
        if(self.user_type=="student"):
            data = {
                "email": request.POST.get("email"),
                "first_name": request.POST.get("first_name"),
                "last_name": request.POST.get("last_name"),
                "roll_number": request.POST.get("roll"),
                "phone_number": request.POST.get("phone"),
                "password": make_password(request.POST.get("password"))
            }
            serializer = UserSerializer(data=data)
            if(serializer.is_valid()):
                user = serializer.save()
                student_data = {
                    "user": user.user_id,
                    "roll_number": data["roll_number"],
                    "phone_number": data["phone_number"]
                }
                serializer = StudentSerializer(data=student_data)
                if(serializer.is_valid()):
                    serializer.save()
                else:
                    user.delete()
                    return Response({"error":"Invalid User Data"}, template_name="error_page.html", status=status.HTTP_400_BAD_REQUEST)
            else:
                return Response({"error":"Invalid User Data"}, template_name="error_page.html", status=status.HTTP_400_BAD_REQUEST)
            return Response(template_name="student_login.html", status=status.HTTP_201_CREATED)

class login(APIView):
    user_type = "student"
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):
        if(self.user_type=="student"):
            return Response(template_name="student_login.html", status=status.HTTP_200_OK)
    
    def post(self, request):
        user = authenticate(email=request.POST.get("email"), password=request.POST.get("password"))
        user_check = self.check_user(user)
        if(not user_check[0]):
            return Response({"error":user_check[1]}, template_name="error_page.html", status=status.HTTP_400_BAD_REQUEST)
        if(self.user_type=="student"):
            # Checking Student
            try:
                student = user.student
            except Exception as e:
                return Response({"error":"Not a valid Student."}, template_name="error_page.html", status=status.HTTP_400_BAD_REQUEST)
            user_serializer_data = UserSerializer(user).data
            stud_serializer_data = StudentSerializer(student).data
            student_data = {
                "user_id": user_serializer_data.get("user_id"),
                "email": user_serializer_data.get("email"),
                "first_name": user_serializer_data.get("first_name"),
                "last_name": user_serializer_data.get("last_name"),
                "roll_number": stud_serializer_data.get("roll_number"),
                "phone_number": stud_serializer_data.get("phone_number"),
                "is_allotted": stud_serializer_data.get("is_allotted"),
            }
            rooms = Room.objects.all()
            rooms_data = []
            for room in rooms:
                room_data = {
                    "room_number": room.room_number,
                    "roll_number": room.roll_number,
                }
                if(room.roll_number!="0"):
                    # Room is allotted
                    curr_student = Student.objects.filter(roll_number=room.roll_number)
                    if(curr_student.exists() and len(curr_student)==1):
                        curr_stud_serializer_data = StudentSerializer(curr_student[0]).data
                        curr_user_serializer_data = UserSerializer(curr_student[0].user).data
                        curr_student_data = {
                            "user_id": curr_user_serializer_data.get("user_id"),
                            "email": curr_user_serializer_data.get("email"),
                            "first_name": curr_user_serializer_data.get("first_name"),
                            "last_name": curr_user_serializer_data.get("last_name"),
                            "roll_number": curr_stud_serializer_data.get("roll_number"),
                            "phone_number": curr_stud_serializer_data.get("phone_number"),
                            "is_allotted": curr_stud_serializer_data.get("is_allotted"),
                        }
                        room_data.update(curr_student_data)
                rooms_data.append(room_data)
        return Response(data={"student": student_data, "rooms": rooms_data}, template_name="homepage.html", status=status.HTTP_200_OK)
    
    def check_user(self, user):
        if(not user):
            return False, "User is not authenticated."
        if(not user.is_active):
            return False, "User is not active."
        return True, "Valid User."
        
class roomAllocate(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    
    def post(self, request, user_id, room_number):
        try:
            user = User.objects.get(user_id=user_id)
            student = user.student
            room = Room.objects.get(room_number=room_number)
            if(room.roll_number=="0"):
                room.roll_number = student.roll_number
                room.save()
                student.is_allotted = True
                student.save()
                return JsonResponse(data={"success": True})
            return JsonResponse(data={"success": False})
        except Exception as e:
            return JsonResponse(data={"success": False})

class user_logout(APIView):

    def get(self, request):
        logout(request)
        return redirect("allocation:index")

allocation/templates/base.html
{% load rest_framework %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
  {% block title_block %}
  {% endblock %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style media="screen">

       #ftr{
         padding: 20px;
       }

       .fa{
             font-size: 23px;
             width: 60px;
             text-align: center;
             text-decoration: none;
             margin: 5px 2px;
             border-radius: 50%;
       }
       .fa:hover{
             opacity: 1;
             text-decoration: none;
           }

       .list-wrapper{
   		  	margin:5px;
   		  	padding: 5px;
   		  	cursor: pointer;
   		  	border-bottom: 1px solid  #e9e9e9;
   		  	color: #686868;
   			}
        .error{
          color:red;
          font-size: 10px;
        }
        .navbar-link{
          font-weight: bold;
        }
        h2{
          color: #583e81;
          font-weight: bold;
        }
        h4{
          color: #583e81;
        }

   </style>
   {% block head_block %}
   {% endblock %}

</head>
<body>

  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>

</body>
</html>

allocation/templates/error_page.html
{% extends "base.html" %}

{% block body_block %}
<div class="jumbotron">
  <p class='error'>{{error}}</p>
  <p><a href="{% url 'allocation:index' %}">Return to Home</a></p>
</div>

{% endblock %}

allocation/templates/homepage.html
{% extends "base.html" %}

{% block head_block %}
<style media="screen">

    .showme {
        display: none;
    }

    .card:hover .showme {
        display: block;
    }

    #myBtn {
        display: block;
        position: fixed;
        bottom: 20px;
        right: 30px;
        z-index: 99;
        font-size: 18px;
        border: none;
        outline: none;
        background-color: red;
        color: white;
        cursor: pointer;
        padding: 15px;
        border-radius: 4px;
    }

    #myBtn:hover {
        background-color: #555;
    }

</style>

<script>
    var mybutton = document.getElementById("myBtn");

    // When the user scrolls down 20px from the top of the document, show the button
    window.onscroll = function() {scrollFunction()};

    function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        mybutton.style.display = "block";
    } else {
        mybutton.style.display = "none";
    }
    }

    // When the user clicks on the button, scroll to the top of the document
    function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
    }
</script>

{% endblock %}

{% block body_block %}
<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

<h2>Hello {{student.first_name}} {{student.last_name}}</h2>
<a class="btn btn-primary" style="text-align: right;" href="{% url 'allocation:logout' %}" role="button">Logout</a>
<br>
<br>
<br>

<div>
    <div class="card-columns" id="cards">
    </div>
</div>

<div>
    <a class="btn btn-primary btn-lg" role="button" id="confirm">Confirm</a>
</div>

{{ student|json_script:"student" }}
{{ rooms|json_script:"rooms" }}
<script>
    let confirmButton = document.getElementById("confirm");
    confirmButton.style.display = "none";

    const student = JSON.parse(document.getElementById('student').textContent);
    const rooms = JSON.parse(document.getElementById('rooms').textContent);

    let cards = document.getElementById("cards");
    let selectedCard = null;
    let selectedRoomNumber = null;
    for(let i=0; i<rooms.length; i++) {
        let room = rooms[i];
        let div1 = document.createElement("div");
        div1.className = "card";
        div1.style.maxWidth = "18rem";
        div1.style.backgroundColor = "red";
        if(room.roll_number==="0") {
            div1.style.backgroundColor = "grey";
            if(!student.is_allotted) {
                div1.onclick = function() {
                    if(selectedCard!=null) {
                        selectedCard.style.backgroundColor = "grey";
                    }
                    div1.style.backgroundColor = "pink";
                    selectedCard = div1;
                    selectedRoomNumber = room.room_number;
                    console.log(selectedRoomNumber);
                    confirmButton.style.display = "block";
                }
            }
            
        }
        if(room.roll_number===student.roll_number) {
            div1.style.backgroundColor = "green";
        }
        let div2 = document.createElement("div");
        div2.className = "card-body";
        let head5 = document.createElement("h5");
        head5.className = "card-title";
        head5.innerText = room.room_number;
        div2.appendChild(head5);
        if(room.roll_number!="0") {
            let p1 = document.createElement("P");
            let p2 = document.createElement("P");
            let p3 = document.createElement("P");
            p1.innerText = "Allocated to: "+room.first_name+" "+room.last_name;
            p2.innerText = "Roll No: "+room.roll_number;
            p3.innerText = "Phone: "+room.phone_number;
            p1.className = "showme";
            p2.className = "showme";
            p3.className = "showme";
            div2.appendChild(p1);
            div2.appendChild(p2);
            div2.appendChild(p3);
        }
        div1.appendChild(div2);
        cards.appendChild(div1);
    }
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrftoken = getCookie('csrftoken');
    confirmButton.onclick = function() {
        if(selectedRoomNumber!=null) {
            console.log(selectedRoomNumber);
            var url = "allocate/"+student.user_id+"/"+selectedRoomNumber;
            $.ajax({
                type: "POST",
                url: url,
                data: {
                    csrfmiddlewaretoken: csrftoken,
                },
                success: function(data) {
                    window.location.reload();
                }
            })
        }
    }
</script>

{% endblock %}

allocation/templates/index.html
{% extends "base.html" %}

{% block body_block %}
<h2>Room Allocation Portal</h2>
<div class="jumbotron">
  {% if message %}
    <div class="alert alert-success">
      <h3>Files successfully uploaded!</h3>
    </div>
  {% endif %}
  <h3>Select User Type</h3>
  <br>
  <ul>
    <li>  <p> <a href="{% url 'admin:index' %}">Admin</a></p></li>
    <li>  <p> <a href="{% url 'allocation:student_login' %}">Student</a></p></li>
  </ul>
</div>


{% endblock %}

allocation/templates/student_login.html
{% extends "base.html" %}
{% block body_block %}
<script type="text/javascript">
function reset() {
  document.getElementById("gcs_form").reset();
}
</script>
<h2>Student Login</h2>

<div id="gcs_form" class="jumbotron">
  <form action="{% url 'allocation:student_login' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" id="email" name="email" value="" placeholder="Please enter your email" required>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Please enter your password" required>
      </div>

      <div>
          <button type="submit" class="btn btn-primary" onsubmit="reset()">Submit</button>
      </div>
  </form>
  <div class="text-center">
    <a class="btn btn-primary" href="{% url 'allocation:student_signup' %}">Sign Up</a>
  </div>
</div>

{% endblock %}

allocation/templates/student_signup.html
{% extends "base.html" %}
{% block body_block %}
<script type="text/javascript">
function reset() {
  document.getElementById("gcs_form").reset();
}
</script>
<h2>Student SignUp</h2>

<div id="gcs_form" class="jumbotron">
  <form action="{% url 'allocation:student_signup' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" id="email" name="email" value="" placeholder="Please enter your email" required>
      </div>

      <div class="form-group">
        <label for="first_name">First Name</label>
        <input type="text" class="form-control" id="first_name" name="first_name" value="" placeholder="Please enter your first name" required>
      </div>

      <div class="form-group">
        <label for="last_name">Last Name</label>
        <input type="text" class="form-control" id="last_name" name="last_name" value="" placeholder="Please enter your last name" required>
      </div>

      <div class="form-group">
        <label for="roll">Roll</label>
        <input type="text" class="form-control" id="roll" name="roll" value="" placeholder="Please enter your roll" required>
      </div>     

      <div class="form-group">
        <label for="phone">Phone</label>
        <input type="text" class="form-control" id="phone" name="phone" value="" placeholder="Please enter your phone number" required>
      </div>     

      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Please enter your password" required>
      </div>

      <div>
          <button type="submit" class="btn btn-primary" onsubmit="reset()">Submit</button>
      </div>
  </form>
  <div class="text-center">
    <a class="btn btn-primary" href="{% url 'allocation:student_login' %}">Log In</a>
  </div>
</div>

{% endblock %}